completed undo/redo for assign
AY1920S2-CS2103-W14-1/main pull request #195
Opened 2020-04-08 17:16 UTC by ivanteejj

2020-04-08 19:14 UTC, tiendat161 requested changes

2020-04-08 19:14 UTC, tiendat161 commented on src/main/java/seedu/address/model/modelGeneric/AddressBookGeneric.java
> +    public void remove(ID id) {
I think we should't make remove a void method as old implementation doesn't affect removing an object and it is more similar to remove method in java api which returns removed object.

2020-04-08 19:22 UTC, tiendat161 commented on src/main/java/seedu/address/model/modelGeneric/AddressBookGeneric.java
> +    public void remove(ID id) {
nvm I think it's ok our remove/delete method declared in Model also void

2020-04-08 19:23 UTC, tiendat161 approved these changes

2020-04-09 01:03 UTC, h12567 approved these changes

2020-04-09 01:03 UTC, merged